-- T_EXTERNAL_SYSTEM_AAA is a reference table defined somewhere in configuration : we should check before that the key doesn't exist already
 INSERT INTO T_EXTERNAL_SYSTEM_AAA(EXTERNAL_SYSTEM_ID, EXTERNAL_SYSTEM_CODE, EXTERNAL_SYSTEM_LBL, IS_VISIBLE,IS_EXTERNAL,
 IS_AAA_AUTHO, DISPLAY_ORDER, IS_PUSHER, AUTHO_SOURCE_DESC, IS_ACTIVITY_REPORT)
 VALUES(S_EXTERNAL_SYSTEM_PCL.NEXTVAL, 'AAA_MANUAL_AUTHO', 'AAA MANUAL AUTHO', 0, 0, 0, NULL, 0,
 'indicates if the system is AAA manual autho', 1)
 /


 -- T_INTERNAL_SYSTEM_AAA is NOT a reference table - no need to check anything
 INSERT INTO T_INTERNAL_SYSTEM_AAA(EXTERNAL_SYSTEM_ID, EXTERNAL_SYSTEM_CODE, EXTERNAL_SYSTEM_LBL, IS_VISIBLE,IS_EXTERNAL,
 IS_AAA_AUTHO, DISPLAY_ORDER, IS_PUSHER, AUTHO_SOURCE_DESC, IS_ACTIVITY_REPORT)
 VALUES(S_EXTERNAL_SYSTEM_PCL.NEXTVAL, 'AAA_MANUAL_AUTHO', 'AAA MANUAL AUTHO', 0, 0, 0, NULL, 0,
 'indicates if the system is AAA manual autho', 1)
 /
