INSERT INTO T_SOME_TABLE(SOME_ID, SOME_CODE, SOME_LABEL, SOME_DESC)
values(SOME_SEQ.NEXTVAL, 'SOME_CODE', 'some label',
'some desc')
/

INSERT INTO T_SOME_TABLE(SOME_ID, SOME_CODE, SOME_LABEL, SOME_DESC)
values(SOME_SEQ.NEXTVAL, 'SOME_CODE2', 'some label2',
'some desc2')
/




